# Generated by Django 2.0.10 on 2019-02-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
