# Generated by Django 2.0.13 on 2019-02-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='email',
            new_name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
