# Generated by Django 2.0.13 on 2019-02-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190213_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='resource',
            name='uuid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='resources',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
