# Generated by Django 2.0.13 on 2019-02-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190214_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='uuid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
